import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import type {AssetRequest,AssetManifestItem} from './types';
import {resolveProvider} from './provider';
import {imageAdapter,videoAdapter} from './factory';

export async function produceAssets(project:string) {
  const dir=path.resolve('projects',project);
  const planPath=path.join(dir,'asset-plan.json');
  if (!fs.existsSync(planPath)) throw new Error(`Missing ${planPath}`);
  const plan:AssetRequest[]=JSON.parse(fs.readFileSync(planPath,'utf8'));
  const manifest:AssetManifestItem[]=[];

  for (const asset of plan) {
    if (!['image','video'].includes(asset.type)) continue;

    const kind=asset.type as 'image'|'video';
    const provider=resolveProvider(kind,asset.providerPreference);
    const ext=kind==='image'?'.png':'.mp4';
    const rel=`assets/${project}/generated/${asset.id}${ext}`;
    const output=path.resolve('public',rel);

    const adapter=kind==='image'?imageAdapter(provider.name):videoAdapter(provider.name);
    let result=await adapter.generate({
      id:asset.id,
      project,
      prompt:asset.prompt ?? asset.id,
      outputPath:output,
      durationSeconds:asset.durationSeconds ?? 5,
      width:1920,
      height:1080
    });

    if (!result.ok && provider.name !== 'local') {
      const fallback=kind==='image'?imageAdapter('local'):videoAdapter('local');
      result=await fallback.generate({
        id:asset.id,project,prompt:asset.prompt ?? asset.id,
        outputPath:output,durationSeconds:asset.durationSeconds ?? 5,width:1920,height:1080
      });
    }

    manifest.push({
      id:asset.id,
      sceneId:asset.sceneId,
      type:asset.type,
      path:result.path ? path.relative(path.resolve('public'),result.path).replaceAll('\\','/') : rel,
      source:'generated',
      provider:result.provider,
      prompt:asset.prompt,
      provenance:`Generated by ${result.provider}`,
      approved:result.ok
    });
  }

  fs.writeFileSync(path.join(dir,'asset-manifest.json'),JSON.stringify(manifest,null,2));
  return manifest;
}
